apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: servicemon-operator
  template:
    metadata:
      labels:
        name: servicemon-operator
    spec:
      serviceAccountName: servicemon-operator
      containers:
        - name: servicemon-operator
          image: jpweber/servicemon-operator:0.1.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - servicemon-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            # - name: WATCH_NAMESPACE
            #   value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "servicemon-operator"
